version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: npm i
      - run: npm run lint
      - save_cache:
          paths:
            - ~/
          key: npm_package

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - restore_cache:
          key: npm_package
      - run: npm i
      - run: npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - restore_cache:
          key: npm_package
      - run: npm i
      - run: npm audit

workflows:
  project:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test