version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/react-slingshot
    steps:
      - run: npm i
      - run: npm run lint
      - save_cache:
          paths:
            - /src/node_modules
          key: "npm_package"
      
  test:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/react-slingshot
    steps:
      - restore_cache:
          key: "npm_package"
      - run: ls -ltrh
      - run: npm i
      - run: npm audit

  analyze:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/react-slingshot
    steps:
      - restore_cache:
          key: "npm_package"
      - run: npm i
      - run: npm run test
workflows:
  project:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
